/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codei.basicjava;

import org.junit.Test;
import static org.junit.Assert.*;

public class MathsLibraryTest {
    @Test public void testSomeLibraryMethod() {
        MathsLibrary mathsLibrary = new MathsLibrary();
        assertTrue(mathsLibrary.add(4, 5) == 9);
    }
}
